server:
  address: 127.0.0.1
  port: 10001

spring:
  application:
    name: ExperienceService
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: false

springdoc:
  swagger-ui:
    path: /documentation

persistence:
  host: jagster-development-do-user-9861309-0.b.db.ondigitalocean.com
  port: 25060
  username: experience_service
  password: AVNS__27QytIOO_SGHTzEWxH
  database: experience_database