name: Experience Project Jobs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:

  doesTheCodeBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn --batch-mode compile -DskipTests

  doesTheCodePassTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn --batch-mode test

  soBuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package -DskipTests

      - name: Checkout the variables and secrets
        run: echo "Username ${{ secrets.USERNAME }}, Token ${{ secrets.TOKEN }}, Repository ${{ github.repository }}, Actor ${{ github.actor }}"

      - name: Login to docker container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push the docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: orionbeauny/experience_project:latest
          load: false