name: Experience Service Jobs

on: [ push ]

jobs:

  build_jar_file_and_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package -DskipTests

      - name: Upload the jar file
        uses: actions/upload-artifact@v3
        with:
          name: experience_jar
          path: target/*.jar

      - name: Checkout the secrets
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: echo "Theses secrets $USERNAME and $TOKEN are encrypted."

      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push the docker image
        uses: docker/build-push-action@v3
        env:
          REGISTRY: ghcr.io
          NAMESPACE: orionbs
          IMAGE: experience_service
          TAG: latest
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
          load: false