name: Experience Service Jobs

on: [ push ]

jobs:

  build_jar_file_and_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v2

      - name: Checkout the variables.
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: echo "Hello $USERNAME, your token is $TOKEN."

      - name: Set up jdk 17.
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package -DskipTests

      - name: Upload the jar file
        uses: actions/upload-artifact@v3
        with:
          name: experience_jar
          path: /*.jar

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push the docker image.
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          tags: experience_service:latest

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "experience_service:latest"