name: publish

on: [push]

jobs:
  publish-web-interface-image:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository.
        uses: actions/checkout@v2

      - name: Set up jdk 17.
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        run: mvn --batch-mode --update-snapshots package -DskipTests


      - name: Login to github container registry.
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push the docker image.
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: web_interface:latest